--
-- Table structure for table `waterways_guide`
--

CREATE TABLE `#__waterways_guide` (
  `GuideID` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `GuideNo` bigint(20) NOT NULL DEFAULT '0',
  `GuideVer` smallint(6) NOT NULL DEFAULT '0',
  `GuideCountry` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GuideWaterway` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GuideSummary` longtext COLLATE utf8mb4_unicode_ci,
  `GuideName` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GuideLatLong` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GuideLocation` longtext COLLATE utf8mb4_unicode_ci,
  `GuideRef` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GuideMooring` longtext COLLATE utf8mb4_unicode_ci,
  `GuideFacilities` longtext COLLATE utf8mb4_unicode_ci,
  `GuideCodes` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GuideCosts` longtext COLLATE utf8mb4_unicode_ci,
  `GuideRating` int(11) DEFAULT '0',
  `GuideAmenities` longtext COLLATE utf8mb4_unicode_ci,
  `GuideContributors` longtext COLLATE utf8mb4_unicode_ci,
  `GuideRemarks` longtext COLLATE utf8mb4_unicode_ci,
  `GuideLat` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '51.1',
  `GuideLong` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT '2.2',
  `GuideOrder` decimal(10,2) DEFAULT NULL,
  `GuideDocs` longtext COLLATE utf8mb4_unicode_ci,
  `GuidePostingDate` datetime DEFAULT NULL,
  `GuideCategory` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GuideUpdate` datetime DEFAULT NULL,
  `GuideStatus` tinyint(3) UNSIGNED DEFAULT NULL,
  `GuideEditorMemNo` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`GuideID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `#__waterways_guide_requests` (
  `memberid` bigint(20) NOT NULL DEFAULT '0',
  `GuideCountry` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GuideWaterway` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GuideRequestDate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `GuideRequestMethod` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `GuideRequestStatus` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `#__waterways_guide_services` (
  `ID` bigint(20) NOT NULL DEFAULT 0,
  `ServiceID` varchar(4) NOT NULL DEFAULT '',
  `ServiceDescGB` mediumtext DEFAULT NULL,
  `ServiceHelpGB` varchar(100) DEFAULT NULL,
  `ServiceCategory` mediumtext DEFAULT NULL,
  `ServiceSortOrder` tinyint(3) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `#__waterways_guide_country` (
  `iso` char(2) NOT NULL DEFAULT '',
  `name` varchar(80) NOT NULL DEFAULT '',
  `printable_name` varchar(80) NOT NULL DEFAULT '',
  `iso3` char(3) DEFAULT NULL,
  `numcode` smallint(6) DEFAULT NULL,
  `postzone` char(3) DEFAULT NULL,
  PRIMARY KEY (`iso`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `#__waterways_guide_country` (`iso`, `name`, `printable_name`, `iso3`, `numcode`, `postzone`) VALUES
('AD', 'ANDORRA', 'Andorra', 'AND', 20, 'EU'),
('AE', 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'ARE', 784, 'Z1'),
('AF', 'AFGHANISTAN', 'Afghanistan', 'AFG', 4, 'Z1'),
('AG', 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'ATG', 28, 'Z1'),
('AI', 'ANGUILLA', 'Anguilla', 'AIA', 660, 'Z1'),
('AL', 'ALBANIA', 'Albania', 'ALB', 8, 'EU'),
('AM', 'ARMENIA', 'Armenia', 'ARM', 51, 'EU'),
('AN', 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'ANT', 530, 'Z1'),
('AO', 'ANGOLA', 'Angola', 'AGO', 24, 'Z1'),
('AQ', 'ANTARCTICA', 'Antarctica', NULL, NULL, 'Z1'),
('AR', 'ARGENTINA', 'Argentina', 'ARG', 32, 'Z1'),
('AS', 'AMERICAN SAMOA', 'American Samoa', 'ASM', 16, 'Z1'),
('AT', 'AUSTRIA', 'Austria', 'AUT', 40, 'EU'),
('AU', 'AUSTRALIA', 'Australia', 'AUS', 36, 'Z2'),
('AW', 'ARUBA', 'Aruba', 'ABW', 533, 'Z1'),
('AZ', 'AZERBAIJAN', 'Azerbaijan', 'AZE', 31, 'EU'),
('BA', 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BIH', 70, 'EU'),
('BB', 'BARBADOS', 'Barbados', 'BRB', 52, 'Z1'),
('BD', 'BANGLADESH', 'Bangladesh', 'BGD', 50, 'Z1'),
('BE', 'BELGIUM', 'Belgium', 'BEL', 56, 'EU'),
('BF', 'BURKINA FASO', 'Burkina Faso', 'BFA', 854, 'Z1'),
('BG', 'BULGARIA', 'Bulgaria', 'BGR', 100, 'EU'),
('BH', 'BAHRAIN', 'Bahrain', 'BHR', 48, 'Z1'),
('BI', 'BURUNDI', 'Burundi', 'BDI', 108, 'Z1'),
('BJ', 'BENIN', 'Benin', 'BEN', 204, 'Z1'),
('BM', 'BERMUDA', 'Bermuda', 'BMU', 60, 'Z1'),
('BN', 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BRN', 96, 'Z1'),
('BO', 'BOLIVIA', 'Bolivia', 'BOL', 68, 'Z1'),
('BR', 'BRAZIL', 'Brazil', 'BRA', 76, 'Z1'),
('BS', 'BAHAMAS', 'Bahamas', 'BHS', 44, 'Z1'),
('BT', 'BHUTAN', 'Bhutan', 'BTN', 64, 'Z1'),
('BV', 'BOUVET ISLAND', 'Bouvet Island', NULL, NULL, 'Z1'),
('BW', 'BOTSWANA', 'Botswana', 'BWA', 72, 'Z1'),
('BY', 'BELARUS', 'Belarus', 'BLR', 112, 'EU'),
('BZ', 'BELIZE', 'Belize', 'BLZ', 84, 'Z1'),
('CA', 'CANADA', 'Canada', 'CAN', 124, 'Z1'),
('CC', 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', NULL, NULL, 'Z1'),
('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Congo, the Democratic Republic of the', 'COD', 180, 'Z1'),
('CF', 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CAF', 140, 'Z1'),
('CG', 'CONGO', 'Congo', 'COG', 178, 'Z1'),
('CH', 'SWITZERLAND', 'Switzerland', 'CHE', 756, 'EU'),
('CI', 'COTE D\'IVOIRE', 'Cote D\'Ivoire', 'CIV', 384, 'Z1'),
('CK', 'COOK ISLANDS', 'Cook Islands', 'COK', 184, 'Z1'),
('CL', 'CHILE', 'Chile', 'CHL', 152, 'Z1'),
('CM', 'CAMEROON', 'Cameroon', 'CMR', 120, 'Z1'),
('CN', 'CHINA', 'China', 'CHN', 156, 'Z1'),
('CO', 'COLOMBIA', 'Colombia', 'COL', 170, 'Z1'),
('CR', 'COSTA RICA', 'Costa Rica', 'CRI', 188, 'Z1'),
('CS', 'SERBIA AND MONTENEGRO', 'Serbia and Montenegro', NULL, NULL, 'EU'),
('CU', 'CUBA', 'Cuba', 'CUB', 192, 'Z1'),
('CV', 'CAPE VERDE', 'Cape Verde', 'CPV', 132, 'Z1'),
('CX', 'CHRISTMAS ISLAND', 'Christmas Island', NULL, NULL, 'Z1'),
('CY', 'CYPRUS', 'Cyprus', 'CYP', 196, 'EU'),
('CZ', 'CZECH REPUBLIC', 'Czech Republic', 'CZE', 203, 'EU'),
('DE', 'GERMANY', 'Germany', 'DEU', 276, 'EU'),
('DJ', 'DJIBOUTI', 'Djibouti', 'DJI', 262, 'Z1'),
('DK', 'DENMARK', 'Denmark', 'DNK', 208, 'EU'),
('DM', 'DOMINICA', 'Dominica', 'DMA', 212, 'Z1'),
('DO', 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DOM', 214, 'Z1'),
('DZ', 'ALGERIA', 'Algeria', 'DZA', 12, 'Z1'),
('EC', 'ECUADOR', 'Ecuador', 'ECU', 218, 'Z1'),
('EE', 'ESTONIA', 'Estonia', 'EST', 233, 'EU'),
('EG', 'EGYPT', 'Egypt', 'EGY', 818, 'Z1'),
('EH', 'WESTERN SAHARA', 'Western Sahara', 'ESH', 732, 'Z1'),
('ER', 'ERITREA', 'Eritrea', 'ERI', 232, 'Z1'),
('ES', 'SPAIN', 'Spain', 'ESP', 724, 'EU'),
('ET', 'ETHIOPIA', 'Ethiopia', 'ETH', 231, 'Z1'),
('FI', 'FINLAND', 'Finland', 'FIN', 246, 'EU'),
('FJ', 'FIJI', 'Fiji', 'FJI', 242, 'Z1'),
('FK', 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FLK', 238, 'Z1'),
('FM', 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FSM', 583, 'Z1'),
('FO', 'FAROE ISLANDS', 'Faroe Islands', 'FRO', 234, 'EU'),
('FR', 'FRANCE', 'France', 'FRA', 250, 'EU'),
('GA', 'GABON', 'Gabon', 'GAB', 266, 'Z1'),
('GB', 'UNITED KINGDOM', 'United Kingdom', 'GBR', 826, 'UK'),
('GD', 'GRENADA', 'Grenada', 'GRD', 308, 'Z1'),
('GE', 'GEORGIA', 'Georgia', 'GEO', 268, 'EU'),
('GF', 'FRENCH GUIANA', 'French Guiana', 'GUF', 254, 'Z1'),
('GH', 'GHANA', 'Ghana', 'GHA', 288, 'Z1'),
('GI', 'GIBRALTAR', 'Gibraltar', 'GIB', 292, 'EU'),
('GL', 'GREENLAND', 'Greenland', 'GRL', 304, 'EU'),
('GM', 'GAMBIA', 'Gambia', 'GMB', 270, 'Z1'),
('GN', 'GUINEA', 'Guinea', 'GIN', 324, 'Z1'),
('GP', 'GUADELOUPE', 'Guadeloupe', 'GLP', 312, 'Z1'),
('GQ', 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GNQ', 226, 'Z1'),
('GR', 'GREECE', 'Greece', 'GRC', 300, 'EU'),
('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', NULL, NULL, 'Z1'),
('GT', 'GUATEMALA', 'Guatemala', 'GTM', 320, 'Z1'),
('GU', 'GUAM', 'Guam', 'GUM', 316, 'Z1'),
('GW', 'GUINEA-BISSAU', 'Guinea-Bissau', 'GNB', 624, 'Z1'),
('GY', 'GUYANA', 'Guyana', 'GUY', 328, 'Z1'),
('HK', 'HONG KONG', 'Hong Kong', 'HKG', 344, 'Z1'),
('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', NULL, NULL, 'Z1'),
('HN', 'HONDURAS', 'Honduras', 'HND', 340, 'Z1'),
('HR', 'CROATIA', 'Croatia', 'HRV', 191, 'EU'),
('HT', 'HAITI', 'Haiti', 'HTI', 332, 'Z1'),
('HU', 'HUNGARY', 'Hungary', 'HUN', 348, 'EU'),
('ID', 'INDONESIA', 'Indonesia', 'IDN', 360, 'Z1'),
('IE', 'IRELAND', 'Ireland', 'IRL', 372, 'EU'),
('IL', 'ISRAEL', 'Israel', 'ISR', 376, 'EU'),
('IN', 'INDIA', 'India', 'IND', 356, 'Z1'),
('IO', 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', NULL, NULL, 'Z1'),
('IQ', 'IRAQ', 'Iraq', 'IRQ', 368, 'Z1'),
('IR', 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IRN', 364, 'Z1'),
('IS', 'ICELAND', 'Iceland', 'ISL', 352, 'EU'),
('IT', 'ITALY', 'Italy', 'ITA', 380, 'EU'),
('JM', 'JAMAICA', 'Jamaica', 'JAM', 388, 'Z1'),
('JO', 'JORDAN', 'Jordan', 'JOR', 400, 'Z1'),
('JP', 'JAPAN', 'Japan', 'JPN', 392, 'Z2'),
('KE', 'KENYA', 'Kenya', 'KEN', 404, 'Z1'),
('KG', 'KYRGYZSTAN', 'Kyrgyzstan', 'KGZ', 417, 'Z1'),
('KH', 'CAMBODIA', 'Cambodia', 'KHM', 116, 'Z1'),
('KI', 'KIRIBATI', 'Kiribati', 'KIR', 296, 'Z1'),
('KM', 'COMOROS', 'Comoros', 'COM', 174, 'Z1'),
('KN', 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KNA', 659, 'Z1'),
('KP', 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'Korea, Democratic People\'s Republic of', 'PRK', 408, 'Z1'),
('KR', 'KOREA, REPUBLIC OF', 'Korea, Republic of', 'KOR', 410, 'Z1'),
('KW', 'KUWAIT', 'Kuwait', 'KWT', 414, 'Z1'),
('KY', 'CAYMAN ISLANDS', 'Cayman Islands', 'CYM', 136, 'Z1'),
('KZ', 'KAZAKHSTAN', 'Kazakhstan', 'KAZ', 398, 'EU'),
('LA', 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'Lao People\'s Democratic Republic', 'LAO', 418, 'Z1'),
('LB', 'LEBANON', 'Lebanon', 'LBN', 422, 'Z1'),
('LC', 'SAINT LUCIA', 'Saint Lucia', 'LCA', 662, 'Z1'),
('LI', 'LIECHTENSTEIN', 'Liechtenstein', 'LIE', 438, 'EU'),
('LK', 'SRI LANKA', 'Sri Lanka', 'LKA', 144, 'Z1'),
('LR', 'LIBERIA', 'Liberia', 'LBR', 430, 'Z1'),
('LS', 'LESOTHO', 'Lesotho', 'LSO', 426, 'Z1'),
('LT', 'LITHUANIA', 'Lithuania', 'LTU', 440, 'EU'),
('LU', 'LUXEMBOURG', 'Luxembourg', 'LUX', 442, 'EU'),
('LV', 'LATVIA', 'Latvia', 'LVA', 428, 'EU'),
('LY', 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya', 'LBY', 434, 'Z1'),
('MA', 'MOROCCO', 'Morocco', 'MAR', 504, 'Z1'),
('MC', 'MONACO', 'Monaco', 'MCO', 492, 'EU'),
('MD', 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MDA', 498, 'EU'),
('MG', 'MADAGASCAR', 'Madagascar', 'MDG', 450, 'Z1'),
('MH', 'MARSHALL ISLANDS', 'Marshall Islands', 'MHL', 584, 'Z1'),
('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'Macedonia, the Former Yugoslav Republic of', 'MKD', 807, 'EU'),
('ML', 'MALI', 'Mali', 'MLI', 466, 'Z1'),
('MM', 'MYANMAR', 'Myanmar', 'MMR', 104, 'Z1'),
('MN', 'MONGOLIA', 'Mongolia', 'MNG', 496, 'Z1'),
('MO', 'MACAO', 'Macao', 'MAC', 446, 'Z1'),
('MP', 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MNP', 580, 'Z1'),
('MQ', 'MARTINIQUE', 'Martinique', 'MTQ', 474, 'Z1'),
('MR', 'MAURITANIA', 'Mauritania', 'MRT', 478, 'Z1'),
('MS', 'MONTSERRAT', 'Montserrat', 'MSR', 500, 'Z1'),
('MT', 'MALTA', 'Malta', 'MLT', 470, 'EU'),
('MU', 'MAURITIUS', 'Mauritius', 'MUS', 480, 'Z1'),
('MV', 'MALDIVES', 'Maldives', 'MDV', 462, 'Z1'),
('MW', 'MALAWI', 'Malawi', 'MWI', 454, 'Z1'),
('MX', 'MEXICO', 'Mexico', 'MEX', 484, 'Z1'),
('MY', 'MALAYSIA', 'Malaysia', 'MYS', 458, 'Z1'),
('MZ', 'MOZAMBIQUE', 'Mozambique', 'MOZ', 508, 'Z1'),
('NA', 'NAMIBIA', 'Namibia', 'NAM', 516, 'Z1'),
('NC', 'NEW CALEDONIA', 'New Caledonia', 'NCL', 540, 'Z1'),
('NE', 'NIGER', 'Niger', 'NER', 562, 'Z1'),
('NF', 'NORFOLK ISLAND', 'Norfolk Island', 'NFK', 574, 'Z1'),
('NG', 'NIGERIA', 'Nigeria', 'NGA', 566, 'Z1'),
('NI', 'NICARAGUA', 'Nicaragua', 'NIC', 558, 'Z1'),
('NL', 'NETHERLANDS', 'Netherlands', 'NLD', 528, 'EU'),
('NO', 'NORWAY', 'Norway', 'NOR', 578, 'EU'),
('NP', 'NEPAL', 'Nepal', 'NPL', 524, 'Z1'),
('NR', 'NAURU', 'Nauru', 'NRU', 520, 'Z1'),
('NU', 'NIUE', 'Niue', 'NIU', 570, 'Z1'),
('NZ', 'NEW ZEALAND', 'New Zealand', 'NZL', 554, 'Z2'),
('OM', 'OMAN', 'Oman', 'OMN', 512, 'Z1'),
('PA', 'PANAMA', 'Panama', 'PAN', 591, 'Z1'),
('PE', 'PERU', 'Peru', 'PER', 604, 'Z1'),
('PF', 'FRENCH POLYNESIA', 'French Polynesia', 'PYF', 258, 'Z1'),
('PG', 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PNG', 598, 'Z1'),
('PH', 'PHILIPPINES', 'Philippines', 'PHL', 608, 'Z1'),
('PK', 'PAKISTAN', 'Pakistan', 'PAK', 586, 'Z1'),
('PL', 'POLAND', 'Poland', 'POL', 616, 'EU'),
('PM', 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'SPM', 666, 'Z1'),
('PN', 'PITCAIRN', 'Pitcairn', 'PCN', 612, 'Z1'),
('PR', 'PUERTO RICO', 'Puerto Rico', 'PRI', 630, 'Z1'),
('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', NULL, NULL, 'Z1'),
('PW', 'PALAU', 'Palau', 'PLW', 585, 'Z1'),
('PY', 'PARAGUAY', 'Paraguay', 'PRY', 600, 'Z1'),
('QA', 'QATAR', 'Qatar', 'QAT', 634, 'Z1'),
('RE', 'REUNION', 'Reunion', 'REU', 638, 'Z1'),
('RO', 'ROMANIA', 'Romania', 'ROM', 642, 'EU'),
('RU', 'RUSSIAN FEDERATION', 'Russian Federation', 'RUS', 643, 'EU'),
('RW', 'RWANDA', 'Rwanda', 'RWA', 646, 'Z1'),
('SA', 'SAUDI ARABIA', 'Saudi Arabia', 'SAU', 682, 'Z1'),
('SB', 'SOLOMON ISLANDS', 'Solomon Islands', 'SLB', 90, 'Z1'),
('SC', 'SEYCHELLES', 'Seychelles', 'SYC', 690, 'Z1'),
('SD', 'SUDAN', 'Sudan', 'SDN', 736, 'Z1'),
('SE', 'SWEDEN', 'Sweden', 'SWE', 752, 'EU'),
('SG', 'SINGAPORE', 'Singapore', 'SGP', 702, 'Z1'),
('SH', 'SAINT HELENA', 'Saint Helena', 'SHN', 654, 'Z1'),
('SI', 'SLOVENIA', 'Slovenia', 'SVN', 705, 'EU'),
('SJ', 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen', 'SJM', 744, 'Z1'),
('SK', 'SLOVAKIA', 'Slovakia', 'SVK', 703, 'EU'),
('SL', 'SIERRA LEONE', 'Sierra Leone', 'SLE', 694, 'Z1'),
('SM', 'SAN MARINO', 'San Marino', 'SMR', 674, 'EU'),
('SN', 'SENEGAL', 'Senegal', 'SEN', 686, 'Z1'),
('SO', 'SOMALIA', 'Somalia', 'SOM', 706, 'Z1'),
('SR', 'SURINAME', 'Suriname', 'SUR', 740, 'Z1'),
('ST', 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'STP', 678, 'Z1'),
('SV', 'EL SALVADOR', 'El Salvador', 'SLV', 222, 'Z1'),
('SY', 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SYR', 760, 'Z1'),
('SZ', 'SWAZILAND', 'Swaziland', 'SWZ', 748, 'Z1'),
('TC', 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TCA', 796, 'Z1'),
('TD', 'CHAD', 'Chad', 'TCD', 148, 'Z1'),
('TF', 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', NULL, NULL, 'Z1'),
('TG', 'TOGO', 'Togo', 'TGO', 768, 'Z1'),
('TH', 'THAILAND', 'Thailand', 'THA', 764, 'Z1'),
('TJ', 'TAJIKISTAN', 'Tajikistan', 'TJK', 762, 'EU'),
('TK', 'TOKELAU', 'Tokelau', 'TKL', 772, 'Z1'),
('TL', 'TIMOR-LESTE', 'Timor-Leste', NULL, NULL, 'Z1'),
('TM', 'TURKMENISTAN', 'Turkmenistan', 'TKM', 795, 'EU'),
('TN', 'TUNISIA', 'Tunisia', 'TUN', 788, 'Z1'),
('TO', 'TONGA', 'Tonga', 'TON', 776, 'Z1'),
('TR', 'TURKEY', 'Turkey', 'TUR', 792, 'EU'),
('TT', 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TTO', 780, 'Z1'),
('TV', 'TUVALU', 'Tuvalu', 'TUV', 798, 'Z1'),
('TW', 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TWN', 158, 'Z1'),
('TZ', 'TANZANIA, UNITED REPUBLIC OF', 'Tanzania, United Republic of', 'TZA', 834, 'Z1'),
('UA', 'UKRAINE', 'Ukraine', 'UKR', 804, 'EU'),
('UG', 'UGANDA', 'Uganda', 'UGA', 800, 'Z1'),
('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', NULL, NULL, 'Z1'),
('US', 'UNITED STATES', 'United States', 'USA', 840, 'Z1'),
('UY', 'URUGUAY', 'Uruguay', 'URY', 858, 'Z1'),
('UZ', 'UZBEKISTAN', 'Uzbekistan', 'UZB', 860, 'EU'),
('VA', 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VAT', 336, 'Z1'),
('VC', 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VCT', 670, 'Z1'),
('VE', 'VENEZUELA', 'Venezuela', 'VEN', 862, 'Z1'),
('VG', 'VIRGIN ISLANDS, BRITISH', 'Virgin Islands, British', 'VGB', 92, 'Z1'),
('VI', 'VIRGIN ISLANDS, U.S.', 'Virgin Islands, U.s.', 'VIR', 850, 'Z1'),
('VN', 'VIET NAM', 'Viet Nam', 'VNM', 704, 'Z1'),
('VU', 'VANUATU', 'Vanuatu', 'VUT', 548, 'Z1'),
('WF', 'WALLIS AND FUTUNA', 'Wallis and Futuna', 'WLF', 876, 'Z1'),
('WS', 'SAMOA', 'Samoa', 'WSM', 882, 'Z1'),
('YE', 'YEMEN', 'Yemen', 'YEM', 887, 'Z1'),
('YT', 'MAYOTTE', 'Mayotte', NULL, NULL, 'Z1'),
('ZA', 'SOUTH AFRICA', 'South Africa', 'ZAF', 710, 'Z1'),
('ZM', 'ZAMBIA', 'Zambia', 'ZMB', 894, 'Z1'),
('ZW', 'ZIMBABWE', 'Zimbabwe', 'ZWE', 716, 'Z1'),
('PT', 'PORTUGAL', 'Portugal', 'PRT', 351, 'EU'),
('EU', 'EUROPE', 'Europe', 'EUR', 0, 'EU');
